[package]
name = "flatgfa-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "flatgfa"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["abi3-py38", "multiple-pymethods"] }
flatgfa = { path = "../flatgfa" }
memmap = "0.7.0"
